# Generated by Django 2.0.2 on 2018-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='予算')),
                ('initial_bet', models.IntegerField(blank=True, null=True, verbose_name='初回ベット金額')),
                ('select_or_manual', models.CharField(blank=True, max_length=100, verbose_name='select_or_manual')),
                ('bet_way', models.CharField(blank=True, max_length=100, verbose_name='ベット方法選択')),
                ('fix_or_variable', models.CharField(blank=True, max_length=100, verbose_name='固定か変動か')),
                ('fix_bet', models.IntegerField(blank=True, null=True, verbose_name='定額')),
                ('nanbai', models.FloatField(blank=True, null=True, verbose_name='直近ベットの何倍')),
                ('reset_when_hit', models.NullBooleanField()),
                ('lost_bet_reset', models.IntegerField(blank=True, null=True, verbose_name='連続不的中リセット')),
                ('win_bet_reset', models.IntegerField(blank=True, null=True, verbose_name='連続１着リセット')),
                ('stopbet_bylost', models.IntegerField(blank=True, null=True, verbose_name='連続不的中上限')),
                ('stopbet_bymaxbet', models.IntegerField(blank=True, null=True, verbose_name='次回ベット金額上限')),
                ('stop_when_hit', models.NullBooleanField()),
                ('stop_bymaxprofit', models.IntegerField(blank=True, null=True, verbose_name='合計利益上限')),
                ('target_ninki', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('target_jockey', models.CharField(blank=True, max_length=100, verbose_name='騎手')),
                ('odds_minimum', models.FloatField(blank=True, null=True, verbose_name='単勝オッズ下限')),
                ('odds_max', models.FloatField(blank=True, null=True, verbose_name='単勝オッズ上限')),
                ('countdown_ninki', models.IntegerField(blank=True, null=True, verbose_name='カウントダウン対象人気')),
                ('countdown_jockey', models.CharField(blank=True, max_length=100, verbose_name='カウントダウン対象騎手')),
                ('start_bet_ninki', models.IntegerField(blank=True, null=True, verbose_name='人気着外カウントダウン')),
                ('start_bet_jockey', models.IntegerField(blank=True, null=True, verbose_name='騎手着外カウントダウン')),
                ('target_place', models.IntegerField(blank=True, null=True, verbose_name='対象着')),
            ],
            options={
                'db_table': 'Logic',
            },
        ),
        migrations.CreateModel(
            name='RaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=100, verbose_name='開催日(始）')),
                ('end_date', models.CharField(blank=True, max_length=100, verbose_name='開催日（終）')),
                ('race_place', models.CharField(blank=True, max_length=100, verbose_name='競馬場')),
                ('race_number', models.IntegerField(blank=True, null=True, verbose_name='レース')),
                ('place_number', models.IntegerField(blank=True, null=True, verbose_name='着順')),
                ('win_ninki', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('waku_number1', models.IntegerField(blank=True, null=True, verbose_name='枠番(内）')),
                ('waku_number2', models.IntegerField(blank=True, null=True, verbose_name='枠番（外）')),
                ('uma_number1', models.IntegerField(blank=True, null=True, verbose_name='馬番(内）')),
                ('uma_number2', models.IntegerField(blank=True, null=True, verbose_name='馬番（外）')),
                ('cource', models.CharField(blank=True, max_length=100, verbose_name='コース')),
                ('uma_sex', models.CharField(blank=True, max_length=100, verbose_name='性別')),
                ('uma_age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('uma_name', models.CharField(blank=True, max_length=100, verbose_name='馬名')),
                ('from_distance', models.CharField(blank=True, max_length=100, verbose_name='距離（上限）')),
                ('to_distance', models.CharField(blank=True, max_length=100, verbose_name='距離（下限）')),
                ('trainer', models.CharField(blank=True, max_length=100, verbose_name='調教師')),
                ('jockey', models.CharField(blank=True, max_length=100, verbose_name='騎手')),
                ('from_odds', models.FloatField(blank=True, null=True, verbose_name='単勝（下限）')),
                ('to_odds', models.FloatField(blank=True, null=True, verbose_name='単勝（上限）')),
                ('win_return', models.IntegerField(blank=True, null=True, verbose_name='単勝払戻')),
                ('race_ID', models.IntegerField(blank=True, null=True, verbose_name='race_ID')),
                ('day_ID', models.IntegerField(blank=True, null=True, verbose_name='day_ID')),
                ('number_horse', models.IntegerField(blank=True, null=True, verbose_name='number_horse')),
            ],
            options={
                'db_table': 'RaceData',
            },
        ),
        migrations.CreateModel(
            name='RaceSettei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_place', models.CharField(blank=True, max_length=100, verbose_name='競馬場')),
                ('start_date', models.CharField(blank=True, max_length=100, verbose_name='開催日(始）')),
                ('end_date', models.CharField(blank=True, max_length=100, verbose_name='開催日（終）')),
                ('race_type', models.CharField(blank=True, max_length=100, verbose_name='コース')),
                ('from_distance', models.CharField(blank=True, max_length=100, verbose_name='距離（上限）')),
                ('to_distance', models.CharField(blank=True, max_length=100, verbose_name='距離（下限）')),
                ('number_horse_min', models.IntegerField(blank=True, null=True, verbose_name='出走馬数(min)')),
                ('number_horse_max', models.IntegerField(blank=True, null=True, verbose_name='出走馬数1(max)')),
                ('win_ninki', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('target_jockey', models.CharField(blank=True, max_length=100, verbose_name='騎手')),
                ('odds_minimum', models.FloatField(blank=True, null=True, verbose_name='単勝（下限）')),
                ('odds_max', models.FloatField(blank=True, null=True, verbose_name='単勝（上限）')),
            ],
            options={
                'db_table': 'RaceSettei',
            },
        ),
        migrations.CreateModel(
            name='TargetRaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=100, verbose_name='開催日(始）')),
                ('end_date', models.CharField(blank=True, max_length=100, verbose_name='開催日（終）')),
                ('race_place', models.CharField(blank=True, max_length=100, verbose_name='競馬場')),
                ('race_number', models.IntegerField(blank=True, null=True, verbose_name='レース')),
                ('place_number', models.IntegerField(blank=True, null=True, verbose_name='着順')),
                ('win_ninki', models.IntegerField(blank=True, null=True, verbose_name='人気')),
                ('waku_number1', models.IntegerField(blank=True, null=True, verbose_name='枠番(内）')),
                ('waku_number2', models.IntegerField(blank=True, null=True, verbose_name='枠番（外）')),
                ('uma_number1', models.IntegerField(blank=True, null=True, verbose_name='馬番(内）')),
                ('uma_number2', models.IntegerField(blank=True, null=True, verbose_name='馬番（外）')),
                ('cource', models.CharField(blank=True, max_length=100, verbose_name='コース')),
                ('uma_sex', models.CharField(blank=True, max_length=100, verbose_name='性別')),
                ('uma_age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('uma_name', models.CharField(blank=True, max_length=100, verbose_name='馬名')),
                ('from_distance', models.CharField(blank=True, max_length=100, verbose_name='距離（上限）')),
                ('to_distance', models.CharField(blank=True, max_length=100, verbose_name='距離（下限）')),
                ('trainer', models.CharField(blank=True, max_length=100, verbose_name='調教師')),
                ('jockey', models.CharField(blank=True, max_length=100, verbose_name='騎手')),
                ('from_odds', models.FloatField(blank=True, null=True, verbose_name='単勝（下限）')),
                ('to_odds', models.FloatField(blank=True, null=True, verbose_name='単勝（上限）')),
                ('win_return', models.IntegerField(blank=True, null=True, verbose_name='単勝払戻')),
                ('race_ID', models.IntegerField(blank=True, null=True, verbose_name='race_ID')),
                ('day_ID', models.IntegerField(blank=True, null=True, verbose_name='day_ID')),
                ('number_horse', models.IntegerField(blank=True, null=True, verbose_name='number_horse')),
            ],
            options={
                'db_table': 'TargetRaceData',
            },
        ),
        migrations.CreateModel(
            name='TargetRaceID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_RaceID', models.CharField(blank=True, max_length=1000000000000000, verbose_name='ターゲットレースID')),
            ],
            options={
                'db_table': 'TargetRaceID',
            },
        ),
    ]
