# Generated by Django 2.0.2 on 2018-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesettei',
            name='howmany_race',
            field=models.IntegerField(blank=True, null=True, verbose_name='対象レース数'),
        ),
        migrations.AlterField(
            model_name='racesettei',
            name='number_horse_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='出走馬数(max)'),
        ),
    ]
