# Generated by Django 2.0.2 on 2018-11-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0002_auto_20181119_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesettei',
            name='avg_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均レース間隔数'),
        ),
        migrations.AddField(
            model_name='racesettei',
            name='max_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大レース間隔数'),
        ),
    ]
