# Generated by Django 2.0.2 on 2018-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0003_auto_20181123_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='target_race',
            field=models.IntegerField(blank=True, null=True, verbose_name='ターゲットレース'),
        ),
    ]
