# Generated by Django 2.0.2 on 2018-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0004_logic_target_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='margin',
            field=models.FloatField(blank=True, null=True, verbose_name='マージン'),
        ),
    ]
