# Generated by Django 2.0.2 on 2018-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0005_logic_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='countdown_select',
            field=models.CharField(blank=True, max_length=100, verbose_name='騎手かジョッキーか'),
        ),
    ]
