# Generated by Django 2.0.2 on 2018-12-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0007_auto_20181224_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='avg_interval',
            field=models.FloatField(blank=True, null=True, verbose_name='平均レース間隔'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='bet_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='ベット金額合計'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='count_bet',
            field=models.IntegerField(blank=True, null=True, verbose_name='ベット回数'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='max_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大レース間隔'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='mx',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大連敗数'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='mx_loss',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大損失額'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='mxlost',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大不的中数'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='合計利益'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='profit_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='的中時利益合計'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='recovery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='回収率'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='return_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='払戻合計'),
        ),
    ]
